package:
    name: synapseclient
    version: "1.5.2.dev1"

source:
    path: ../

# patches:
     # List any patch files here
     # - fix.patch

build:
    # noarch_python: True
    # preserve_egg_dir: True
    entry_points:
        - synapse=synapseclient.__main__:main

    # If this is a new build for the same version, increment the build
    # number. If you do not include this key, it defaults to 0.
    number: 1

requirements:
    build:
        - python
        - setuptools
        - requests >=1.2
        - six
        - future
        - backports.csv
        - pandas
        - pysftp

    run:
        - python
        - requests >=1.2
        - six
        - future
        - backports.csv
        - pandas
        - pysftp


test:
    # Python imports
    imports:
        - synapseclient

    commands:
        # You can put test commands to be run here.    Use this to test that the
        # entry points work.

        - synapse --help

    # You can also put a file called run_test.py in the recipe that will be run
    # at test time.

    requires:
        # Put any additional test requirements here.    For example
        - nose
        - mock

about:
    home: https://github.com/Sage-Bionetworks/synapsePythonClient
    license: Apache
    summary: 'Programmatic interface to Synapse services for Python https://www.synapse.org'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
